FROM golang:1.24-alpine

WORKDIR /app

# Install development tools

# Copy go mod files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

RUN go install github.com/air-verse/air@latest

# Copy source code
COPY . .

# Expose port
EXPOSE 8080

# Run with hot reload using air
CMD ["air"]
