#!/bin/bash
# Token Refresh Manual Test Script
# Run this after starting the app to verify token refresh behavior

echo "======================================"
echo "Token Refresh Manual Test"
echo "======================================"
echo ""

echo "Prerequisites:"
echo "1. Backend running (make dev in excalidraw-be/)"
echo "2. Frontend running (npm run dev)"
echo "3. User logged in"
echo ""

echo "Test Steps:"
echo ""
echo "Step 1: Test Page Load Refresh (NEW)"
echo "--------------------------------------"
echo "1. Login to the app"
echo "2. Wait for token to expire (or set short expiry in backend)"
echo "3. Close browser tab completely"
echo "4. Reopen the app URL"
echo ""
echo "Expected Behavior:"
echo "✅ Console shows: [TokenRefresh] Service starting..."
echo "✅ Console shows: [TokenRefresh] Token expired on page load, refreshing..."
echo "✅ Console shows: [TokenRefresh] Refreshing tokens..."
echo "✅ Console shows: [TokenRefresh] Tokens refreshed successfully"
echo "✅ Console shows: [TokenRefresh] Initial refresh successful"
echo "✅ NO 401 errors appear"
echo "✅ App works immediately without errors"
echo ""

echo "Step 2: Check Current Token Expiry"
echo "--------------------------------------"
echo "Open browser console and run:"
echo ""
echo "const token = JSON.parse(localStorage.getItem('auth-storage')).state.accessToken;"
echo "const payload = JSON.parse(atob(token.split('.')[1]));"
echo "console.log('Token expires at:', new Date(payload.exp * 1000));"
echo "console.log('Time until expiry:', Math.floor((payload.exp * 1000 - Date.now()) / 1000), 'seconds');"
echo ""

echo "Step 3: Wait for Token to Expire"
echo "--------------------------------------"
echo "- Keep browser console open"
echo "- Wait for token to expire (or manually set expiry in backend for testing)"
echo "- You should see no background polling requests in Network tab"
echo ""

echo "Step 4: Trigger API Call After Expiry"
echo "--------------------------------------"
echo "Do any of these actions:"
echo "  • Click 'Save' button (save canvas)"
echo "  • Create new file in Sidebar"
echo "  • Send AI chat message"
echo "  • Join a room"
echo ""

echo "Expected Behavior:"
echo "✅ Console shows: [ApiService] 401 Unauthorized, attempting token refresh..."
echo "✅ Console shows: [TokenRefresh] Refreshing tokens..."
echo "✅ Console shows: [TokenRefresh] Tokens refreshed successfully"
echo "✅ Console shows: [ApiService] Token refreshed, retrying request..."
echo "✅ Original API call succeeds"
echo "✅ New token saved in localStorage"
echo ""

echo "Step 5: Test Concurrent Requests"
echo "--------------------------------------"
echo "Expire token again, then:"
echo "  • Click Save + Create File + Send AI message simultaneously"
echo ""
echo "Expected:"
echo "✅ Only ONE refresh request in Network tab"
echo "✅ All 3 requests succeed after refresh completes"
echo ""

echo "Step 6: Test Refresh Token Expired"
echo "--------------------------------------"
echo "Manually expire refresh token (backend testing):"
echo ""
echo "Expected:"
echo "✅ Console shows: [TokenRefresh] Refresh failed, clearing auth"
echo "✅ User automatically logged out"
echo "✅ Redirected to login modal"
echo ""

echo "Step 7: Test AI Proactive Refresh"
echo "--------------------------------------"
echo "Token expires in <30 seconds, send AI message:"
echo ""
echo "Expected:"
echo "✅ Console shows: [AI Service] Token expired, refreshing before request..."
echo "✅ Token refreshed BEFORE streaming starts"
echo "✅ AI response streams without interruption"
echo ""

echo "======================================"
echo "Network Tab Monitoring"
echo "======================================"
echo ""
echo "Old Strategy (Polling):"
echo "  - Request to /api/auth/refresh every 30 seconds"
echo "  - 120 requests per hour"
echo ""
echo "New Strategy (Interceptor):"
echo "  - NO background requests"
echo "  - Refresh only on 401 response"
echo "  - 4-5 requests per hour (depending on token lifetime)"
echo ""

echo "======================================"
echo "Debugging Commands"
echo "======================================"
echo ""
echo "# Check if token refresh service is running"
echo "window.tokenRefreshService = (await import('./services/tokenRefreshService')).tokenRefreshService"
echo ""
echo "# Check token expiry"
echo "window.tokenRefreshService.isTokenExpired()"
echo ""
echo "# Force manual refresh (testing only)"
echo "window.tokenRefreshService.refreshTokens()"
echo ""
echo "# Monitor auth state"
echo "setInterval(() => {"
echo "  const auth = JSON.parse(localStorage.getItem('auth-storage') || '{}');"
echo "  console.log('Auth:', auth.state?.isAuthenticated, 'User:', auth.state?.user?.username);"
echo "}, 5000);"
echo ""

echo "======================================"
echo "Performance Comparison"
echo "======================================"
echo ""
echo "Scenario: 1 hour session, 15min token lifetime"
echo ""
echo "| Metric                  | Old (Polling) | New (Interceptor) |"
echo "|-------------------------|---------------|-------------------|"
echo "| Background requests     | 120           | 0                 |"
echo "| Refresh requests        | ~120          | 4                 |"
echo "| Network overhead        | High          | Low               |"
echo "| Battery impact          | High          | Low               |"
echo "| Request latency added   | 0ms           | ~200ms (on 401)   |"
echo ""

echo "Test completed. Monitor console for any errors."
